{% set name = "hkl" %}
{% set version = "5.1.2.3679" %}
{% set git_hash = "f766ae40b7c1cdccf47c9ef5deae6a1534dc7f2a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  sha256: "bcc510259f279745e42a04aced1074dd7892b68bc83214b86a77323f1d2d0d49"
  url: https://repo.or.cz/hkl.git/snapshot/{{ git_hash }}.tar.gz

build:
  number: 0
  skip: True  # [py<39 or win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - autoconf
    - make
    - pkg-config
  host:
    - autoconf-archive
    - automake
    - conda-verify
    - glib
    - glib-tools
    - gobject-introspection
    - gsl
    - libglib
    - libcblas
    - libtool
    - m4
    - zlib
  run:
    - gobject-introspection
    - pygobject

test:
  requires:
    - conda-verify
    - pip
    - python <3.12

about:
  home: http://repo.or.cz/w/hkl.git
  summary: Synchrotron SOLEIL library for diffractometer operations.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  doc_url: https://people.debian.org/~picca/hkl/hkl.html
  dev_url: http://repo.or.cz/w/hkl.git

extra:
  recipe-maintainers:
    - mrakitin
    - prjemian
