{% set name = "hkl" %}
{% set version = "v5.0.0.3001" %}
{% set tag = "v5.0.0.2173" %}
{% set tarball = "libhkl-v5.0.0.2173-x86_64.tar.gz" %}
{% set license = "COPYING" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bluesky/libhkl/releases/download/{{ tag }}/{{ tarball }}
  sha: 0d36ee67057239f6a439b3f4fecac20df5102627c81bae90f1bc1e3c94e56a90

build:
  number: 0
  skip: True  # [py<38 or py>11 or win or osx]

requirements:
  host:
    - gobject-introspection =1.78.1
    - gsl =2.7
    - pygobject
    - python
  run:
    - python
    - gobject-introspection =1.78.1
    - gsl =2.7
    - numpy
    - pygobject
    # - conda-verify  ?

test:
  commands:
    - ls -lAFgh ${PREFIX}/lib/libhkl.*
    - test -f ${PREFIX}/lib/libhkl.so
    - ldd ${PREFIX}/lib/libhkl.so
    - test ! -f ${PREFIX}/lib/libhkl.a
    - echo "libhkl test starting"
    - ls -lAFgh ${SRC_DIR}
    - test -f ${SRC_DIR}/tests/try_libhkl.py
    - python ${SRC_DIR}/tests/try_libhkl.py
    - echo "libhkl test finished"

about:
  home: http://repo.or.cz/w/hkl.git
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Diffractometer computation library
  doc_url: https://people.debian.org/~picca/hkl/hkl.html
  dev_url: http://repo.or.cz/w/hkl.git

extra:
  recipe-maintainers:
    - mrakitin
    - prjemian
