{% set name = "hkl" %}
# https://repo.or.cz/hkl.git
# git rev-list --count REFERENCE
# sha256sum GIT_HASH.tar.gz
{% set version = "5.1.4.3765" %}
{% set git_hash = "e4de11fc75583bee7bbac661bb6488eb95d210aa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  sha256: "ea5a2d845c12c18ac3230483968ffb3ce1d611e1453814bb5fda7262effb4990"
  url: https://repo.or.cz/hkl.git/snapshot/{{ git_hash }}.tar.gz

build:
  number: 0
  skip: True  # [py<39 or win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - autoconf
    - make
    - pkg-config
  host:
    - autoconf-archive
    - automake
    - conda-verify
    - glib
    - glib-tools
    - gobject-introspection
    - gsl
    - libcblas
    - libglib
    - libtool
    - m4
    - zlib
  run:
    - gobject-introspection
    - libglib
    - pygobject

test:
  requires:
    - conda-verify
    - pip
    - python <3.12
  downstreams:
    # - hklpy  # FIXME: fails due to missing tiled package
    - hklpy2  # does not fail

about:
  home: http://repo.or.cz/w/hkl.git
  summary: Synchrotron SOLEIL library for diffractometer operations.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  doc_url: https://people.debian.org/~picca/hkl/hkl.html
  dev_url: http://repo.or.cz/w/hkl.git

extra:
  recipe-maintainers:
    - mrakitin
    - prjemian
