{% set name = "hkl" %}
{% set version = "5.0.0.3001" %}
{% set commit_hash = "0be5985a8aa893ab9aaffbfb8dc08fce0e4a2d79" %}
{% set sha256 = "074b42c5f3d3bc084ea34cabaca13778a7f0347c1d90d780339a9df3bef8b8cf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://repo.or.cz/{{ name }}.git/snapshot/{{ commit_hash }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - no-docs.patch

build:
  number: 0
  skip: True  # [py<36 or win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - m4
    - make
    - pkg-config
  host:
    - glib
    - gobject-introspection
    - gsl
    - libcblas
    - libiconv
    - pcre
    - pygobject
    - python
  run:
    - python
    - gsl
    - numpy
    - pygobject

test:
  commands:
    - test -f ${PREFIX}/lib/libhkl.so
    - test ! -f ${PREFIX}/lib/libhkl.a

about:
  home: http://repo.or.cz/w/hkl.git
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Diffractometer computation library
  doc_url: https://people.debian.org/~picca/hkl/hkl.html
  dev_url: http://repo.or.cz/w/hkl.git

extra:
  recipe-maintainers:
    - mrakitin
    - prjemian
