{% set name = "hkl" %}
{% set version = "5.0.0.3501" %}
{% set repo_tag = "v1.2.2" %}
{% set tarball = "libhkl-v5.0.0.3501-x86_64.tar.gz" %}
{% set tarball_sha256 = "" %}
{% set license = "COPYING" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bluesky/libhkl/releases/download/{{ repo_tag }}/{{ tarball }}
  sha256: {{ tarball_sha256 }}

build:
  number: 0
  skip: True  # [py<36 or win or osx]

requirements:
  host:
    - gobject-introspection 
    - gsl =2.6
    - libcblas
    - pygobject
    - python
  run:
    - python
    - gobject-introspection 
    - gsl =2.6
    - libcblas
    - numpy
    - pygobject

test:
  commands:
    - ls -lAFgh ${PREFIX}/lib/libhkl.*
    - test -f ${PREFIX}/lib/libhkl.so
    - echo "references these dynamic libraries"
    - ldd ${PREFIX}/lib/libhkl.so
    - test ! -f ${PREFIX}/lib/libhkl.a
    - echo "libhkl test starting"
    - ls -lAFgh ${SRC_DIR}
    - test -f ${RECIPE_DIR}/try_libhkl.py
    - python ${RECIPE_DIR}/try_libhkl.py
    - echo "libhkl test finished"

about:
  home: http://repo.or.cz/w/hkl.git
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Diffractometer computation library
  doc_url: https://people.debian.org/~picca/hkl/hkl.html
  dev_url: http://repo.or.cz/w/hkl.git

extra:
  recipe-maintainers:
    - mrakitin
    - prjemian
