{% set name = "hkl" %}
# https://repo.or.cz/hkl.git
# git rev-list --count REFERENCE
# sha256sum GIT_HASH.tar.gz
{% set version = "5.1.3.3561" %}
{% set git_hash = "90c8704b08238a74f7ad4c9f7bf2692231eb60ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  sha256: "6ad0dcbfbb503835da7b7bf116b78213d538422b9e3c481f2d767d896b62e618"
  url: https://repo.or.cz/hkl.git/snapshot/{{ git_hash }}.tar.gz

build:
  number: 0
  skip: True  # [py<39 or win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - autoconf
    - make
    - pkg-config
  host:
    - autoconf-archive
    - automake
    - conda-verify
    # - glib
    - glib-tools
    - gobject-introspection
    - gsl
    # - libglib
    - libcblas
    - libtool
    - m4
    - zlib
  run:
    - gobject-introspection
    - pygobject

test:
  requires:
    - conda-verify
    - pip
    - python <3.12
  downstreams:
    # - hklpy  # FIXME: fails due to missing tiled package
    - hklpy2  # does not fail

about:
  home: http://repo.or.cz/w/hkl.git
  summary: Synchrotron SOLEIL library for diffractometer operations.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  doc_url: https://people.debian.org/~picca/hkl/hkl.html
  dev_url: http://repo.or.cz/w/hkl.git

extra:
  recipe-maintainers:
    - mrakitin
    - prjemian
